# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI-.NET

on:
  push:
    branches:
    - main
    paths-ignore:
    - '.gitignore'
    - '.gitattributes'
    - '*.md'
    - 'LICENSE*'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '.gitignore'
    - '.gitattributes'
    - '*.md'
    - 'LICENSE*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/OptionsProvider

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release *.sln
    - name: Lint
      run: dotnet format --verify-no-changes --severity info --no-restore *.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release *.sln
    - name: Publish
      if: github.ref == 'refs/heads/main'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
          set -ex
          dotnet pack --configuration Release
          dotnet nuget push OptionsProvider/bin/Release/OptionsProvider.*.nupkg  --source https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate